# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the android-aarch64-php-patches branch
  push:
    branches: [ android-aarch64-php-patches ]
  pull_request:
    branches: [ android-aarch64-php-patches ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 360
    continue-on-error: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell

      # Runs a set of commands using the runners shell
      - name: Get requirements
        run: |
          sudo apt install make
          sudo apt install autoconf
          sudo apt install automake
          sudo apt install libtool
          sudo apt install m4
          sudo apt install wget
          sudo apt install gzip
          sudo apt install bzip2
          sudo apt install bison
          sudo apt install g++
          sudo apt install git
          sudo apt install cmake
          sudo apt install pkg-config
          sudo apt install re2c
        
      - name: Clone and Run
        run: | 
          git clone --recursive https://github.com/pmmp/musl-cross-make.git
          cd musl-cross-make
          cp config.mak.dist config.mak
          make install
